{{ range $sa := .Values.serviceAccounts }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPartialPolicy
metadata:
  name: {{ $sa.name | lower | required "Service Account name is required" }}-sqlinstance-roles
  {{- if $.Values.argoSyncWave }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.argoSyncWave | quote }}
  {{- end }}
  labels:
    {{- include "sqlinstance.labels" $ | nindent 4 }}
    {{- with $.Values.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/{{ $sa.projectId | lower | required "A project ID is required" }}
  bindings:
    {{- if $sa.role }}
    - role: {{ $sa.role }}
    {{- else }}
    - role: organizations/909834982171/roles/cloudsql.serviceaccount.access
    {{- end }}
      members:
        - memberFrom:
            serviceAccountRef:
              name: {{ $sa.name | lower | required "Service Account name is required" }}
---
{{- end }}